version: '3'
services: 
  backend_primary:
    build: 
      context: ./backend
    environment: 
      PORT: 3000
      ROLE: primary
    ports: 
      - 3009:3000

  backend_backup:
    build: 
      context: ./backend
    environment: 
      PORT: 3000
      ROLE: backup
    ports: 
      - 3010:3000
  
  nginx:
    image: nginx:1.16.1 # stable as of dev time
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/sites-enabled:/etc/nginx/sites-enabled/
    ports:
      - 8000:3000
    depends_on: 
      - backend_backup
      - backend_primary
  mongo:
    image: mongo:4.2.6-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678